### ISSUE TITLE
data

### ISSUE THREAD

**Issue by 11140321** [yuanweining/FusionDTA#1]
您好，我想请问一下有了davis_cold数据集，怎么生成drug_cold或者protein_cold的五折交叉验证数据集呀

**Comment by yuanweining** [comment]
你好，你只需要把datahelper.py中#generating cold data的操作复制到`if i == 0:`的外面，然后修改`with open`的文件名为你需要的5个文件名即可。

**Comment by 11140321** [comment]
您好，我这样操作只生成了5个测试集并没有训练集，而且他不需要设置drug_id或者protein_id什么的吗，应该怎么区分生成的是drug_cold还是protein_cold呢

**Comment by yuanweining** [comment]
贴一下你的代码，我看一下吧

**Comment by 11140321** [comment]
for i in range(5):
        train_fold = train_folds[i]
        valid_fold = valid_folds[i]
        for opt in opts:
            rows, cols = np.where(np.isnan(affinity)==False)  
            if opt=='train':
                rows,cols = rows[train_fold], cols[train_fold]
            elif opt=='test':
                rows,cols = rows[valid_fold], cols[valid_fold]
                
            if i == 0:
                #generating standard data
                print('generating standard data')
                with open('data/' + dataset + '_' + opt + '.csv', 'w') as f:
                    f.write('compound_iso_smiles,target_sequence,affinity,protein_id\n')
                    for pair_ind in range(len(rows)):
                        ls = []
                        ls += [ drugs[rows[pair_ind]]  ]
                        ls += [ prots[cols[pair_ind]]  ]
                        ls += [ affinity[rows[pair_ind],cols[pair_ind]]  ]
                        ls += [ cols[pair_ind] ]
                        f.write(','.join(map(str,ls)) + '\n')
                
        #generating cold data
        print('generating cold data')
        if opt=='train':
            with open('data/' + dataset + '_cold' + '.csv', 'w') as f:
                f.write('SMILES,target_sequence,affinity,protein_id,drug_id\n')
                for pair_ind in range(len(rows)):
                    ls = []
                    ls += [ drugs[rows[pair_ind]]  ]
                    ls += [ prots[cols[pair_ind]]  ]
                    ls += [ affinity[rows[pair_ind],cols[pair_ind]]  ]
                    ls += [ cols[pair_ind] ]
                    ls += [ rows[pair_ind] ]
                    f.write(','.join(map(str,ls)) + '\n')
        else:
            with open('data/' + dataset + '_cold' + '.csv', 'a') as f:
                for pair_ind in range(len(rows)):
                    ls = []
                    ls += [ drugs[rows[pair_ind]]  ]
                    ls += [ prots[cols[pair_ind]]  ]
                    ls += [ affinity[rows[pair_ind],cols[pair_ind]]  ]
                    ls += [ cols[pair_ind] ]
                    ls += [ rows[pair_ind] ]
                    f.write(','.join(map(str,ls)) + '\n')

            #5-fold validation data
            print('generating 5-fold validation data')
            with open('data/' + dataset + '/' + dataset + '_' + opt + '_cold' + str(i) + '.csv', 'w') as f:
                f.write('SMILES,target_sequence,affinity,protein_id\n')
                for pair_ind in range(len(rows)):
                    ls = []
                    ls += [ drugs[rows[pair_ind]]  ]
                    ls += [ prots[cols[pair_ind]]  ]
                    ls += [ affinity[rows[pair_ind],cols[pair_ind]]  ]
                    ls += [ cols[pair_ind] ]
                    f.write(','.join(map(str,ls)) + '\n')   
我只按照刚才您说的把generating cold data的代码提到了前面，然后把 #5-fold validation data的with Open文件名修改了一下 麻烦您了，真的十分感谢！！！

**Comment by yuanweining** [comment]
我说错了，应该把代码提到 `for opt in opts:`这个循环中，而不是`if i == 0`

**Comment by yuanweining** [comment]
就是你把代码提到跟i==0同样的缩进下

**Comment by 11140321** [comment]
噢噢噢 那这样分出来的数据集怎么区分是冷蛋白还是冷药物呀

**Comment by yuanweining** [comment]
数据集中不区分这个，在训练的python文件中区分。
```
for i in range(len(drug)):
    if did[i] in did_sample:
        test_drug.append(drug[i])
        test_protein.append(protein[i])
        test_affinity.append(affinity[i])
        test_pid.append(pid[i])
        test_did.append(did[i])
    else:
        train_drug.append(drug[i])
        train_protein.append(protein[i])
        train_affinity.append(affinity[i])
        train_pid.append(pid[i])
        train_did.append(did[i])
```

**Comment by 11140321** [comment]
好的好的，谢谢谢谢！！！
